// Package winres holds the committed Windows resource objects (icon,
// manifest, version info) generated by tools/resgen.
//
// Importing this package for its side effect links the matching
// dumd_windows_<arch>.syso into the binary. It is imported only from
// resources_windows.go, which excludes Wails' own build tags (dev, desktop)
// so this object and Wails' ephemeral <name>-res.syso never reach the linker
// together — two .rsrc sections make the Go linker fail with "too many
// .rsrc sections".
package winres
