// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseApp():Promise<void>;

export function GetRenderedMarkdown():Promise<string>;

export function OpenInBrowser(arg1:string):Promise<void>;
